# Generated by Django 4.2.2 on 2023-06-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('foto', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=100)),
                ('tamanho', models.CharField(max_length=2)),
                ('preco', models.FloatField()),
                ('estadoDaPeca', models.CharField(max_length=100)),
                ('disponibilidade', models.BooleanField()),
            ],
        ),
    ]
