# Generated by Django 4.2.2 on 2023-06-15 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_loja_alter_produto_categoria_produto_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='criacaoEm',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='produto',
            name='disponibilidade',
            field=models.BooleanField(default=False),
        ),
    ]
