# Generated by Django 4.2.2 on 2023-06-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_produto_criacaoem_alter_produto_disponibilidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='criacaoEm',
            new_name='criadoEm',
        ),
    ]
