# Generated by Django 4.2.2 on 2023-06-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0006_alter_produto_estadodapeca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='estadoDaPeca',
            field=models.CharField(choices=[('EXECELENTE', 'Execelente'), ('BOM', 'Bom'), ('DEFEITUOSO', 'Defeituoso')], default='', max_length=100),
        ),
    ]
