# Generated by Django 4.2.2 on 2023-06-16 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0008_alter_endereco_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='endereco',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vitrine.endereco'),
            preserve_default=False,
        ),
    ]
