# Generated by Django 4.2.2 on 2023-06-18 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0013_remove_cliente_endereco_endereco_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoLoja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Endereco',
            new_name='EnderecoCliente',
        ),
        migrations.AlterField(
            model_name='loja',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrine.enderecoloja'),
        ),
    ]
