# Generated by Django 4.2.2 on 2023-06-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0014_enderecoloja_rename_endereco_enderecocliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='logado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loja',
            name='logado',
            field=models.BooleanField(default=False),
        ),
    ]
