# Generated by Django 4.2.2 on 2023-06-26 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0016_remove_cliente_logado_remove_loja_logado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vitrine.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrine.produto')),
            ],
        ),
    ]
