# Generated by Django 4.2.2 on 2023-06-26 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0017_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrine.cliente'),
        ),
    ]
