# Generated by Django 4.2.2 on 2023-06-26 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0018_carrinho_id_alter_carrinho_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrinho',
        ),
    ]
