# Generated by Django 4.2.2 on 2023-06-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0019_delete_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitrine.cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitrine.loja'),
        ),
    ]
