# Generated by Django 4.2.2 on 2023-06-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0020_alter_venda_cliente_alter_venda_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=100000),
        ),
    ]
