# Generated by Django 4.2.2 on 2023-06-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0022_alter_produto_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estadoDaPeca',
            field=models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BOM', 'Bom'), ('DEFEITUOSO', 'Defeituoso')], default='', max_length=100),
        ),
    ]
